# Generated by Django 4.2.1 on 2023-05-13 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exploration",
            fields=[
                (
                    "exploration_rid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metadata", models.JSONField()),
            ],
            options={
                "db_table": "Exploration",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QueryRequest",
            fields=[
                (
                    "query_request_rid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.TextField()),
                ("input", models.JSONField()),
                ("request_date", models.DateTimeField()),
                ("completion_date", models.DateTimeField(null=True)),
                ("result", models.JSONField(null=True)),
            ],
            options={
                "db_table": "QueryRequest",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ExplorationXQueryRequest",
            fields=[
                (
                    "exploration_x_query_request_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("position", models.TextField()),
                (
                    "exploration_rid",
                    models.ForeignKey(
                        db_column="exploration_rid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Exploration",
                        to="query.exploration",
                    ),
                ),
                (
                    "query_request_rid",
                    models.ForeignKey(
                        db_column="query_request_rid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="QueryRequest",
                        to="query.queryrequest",
                    ),
                ),
            ],
            options={
                "db_table": "ExplorationXQueryRequest",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["exploration_rid"],
                        name="Exploration_explora_aff021_idx",
                    ),
                    models.Index(
                        fields=["query_request_rid"],
                        name="Exploration_query_r_c72710_idx",
                    ),
                ],
            },
        ),
    ]
