# Generated by Django 4.2.1 on 2023-05-06 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryRequest",
            fields=[
                (
                    "query_request_rid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.TextField()),
                ("input", models.JSONField()),
                ("result", models.JSONField()),
            ],
            options={
                "db_table": "QueryRequest",
                "managed": True,
            },
        ),
    ]
