# Generated by Django 4.2.1 on 2023-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryRequest",
            fields=[
                (
                    "query_request_rid",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("status", models.TextField()),
                ("input", models.JSONField()),
                ("result", models.JSONField()),
            ],
            options={
                "db_table": "QueryRequest",
            },
        ),
    ]
